package dev.pluglabs.plugtrace.domain;

public enum ChangeType {
    COMPONENT_ADDED,
    COMPONENT_REMOVED,
    VERSION_CHANGED,
    BINARY_CHANGED_SAME_VERSION,
    METADATA_CHANGED,
    CONFIG_HASH_CHANGED,
    RUNTIME_CHANGED,
    LOAD_OUTCOME_CHANGED,
    ISSUE_APPEARED,
    ISSUE_RESOLVED,
    ISSUE_WORSENED
}
